"""Module containing the Export class, which provides ways to export the DB
contents into various formats"""

import matplotlib.pyplot as plt
import pandas as pd

# from export import TECHS
from .search_terms import TECHS


class Export:
    """Class for exporting to various formats, namely csv and plots

    Attributes
    ----------
    None : None
        TODO: Refactor the to_csv to use the init instead

    Methods
    -------
    to_csv(
        year_start: int,
        year_end: int,
        month_step: int = 12,
        category: str = "languages",
    )
        Generates a dict representing the statistics. Used in other class
        methods to display/export the data
    to_csv(stats_dict: dict, filename: str)
        Exports the data dict to a CSV
    to_plot(csv_path: str)
        Plots the data to a popup window
    """

    def __init__(self, database: "Database"):
        self.database = database

    def get_data(
        self,
        year_start: int,
        year_end: int,
        month_step: int = 12,
        category: str = "languages",
    ):
        """Returns a dict representing the statistics

        Parameters
        ----------
        year_start: int
            The starting point of the years to export
        year_end: int
            The ending point of the years to export
        month_step: int = 12
            How often between individual years to export
        category: str = "languages"
            Which section of `search_terms.py` to export

        Returns
        -------
        stats_dict: dict
            The statistics of each technology, per year and count
        """
        data = {"Technology": [], "Count": [], "Year": []}
        # For each technology
        for tech in TECHS[category]:
            # For each year
            for year in list(range(year_start, year_end + 1)):
                names = [tech["name"]] + tech["aliases"]
                for step in range(0, 12, month_step):
                    total_count = 0
                    data["Technology"].append(tech["name"])
                    if step > 0:
                        data["Year"].append(year + round(step / 12, 2))
                    else:
                        data["Year"].append(year)
                    for name in names:
                        total_count += len(
                            self.database.query_postings(
                                year, step + 1, name, tech["case_sensitive"]
                            )
                        )
                    data["Count"].append(total_count)
        return data

    def to_csv(self, stats_dict: dict, filename: str):
        """Exports the data dict to a CSV

        Parameters
        ----------
        stats_dict: dict
            The stats_dict generated by `get_data`
        filename: str
            The filename to save the CSV as
        """
        df = pd.DataFrame(stats_dict)
        df.to_csv(filename, index=False)

    def to_plot(self, csv_path: str):
        """Plots the data to a popup window

        Parameters
        ----------
        csv_path: str
            The path to the .csv file (created from to_csv) to plot
        """
        # Read the CSV data into a DataFrame
        data = pd.read_csv(csv_path)

        # Pivot the data to make it easier to plot
        pivot_data = data.pivot(index="Year", columns="Technology", values="Count")

        # Plotting
        plt.figure(figsize=(10, 6))

        # Line styles, since this many data points is bad
        styles = ["-", "--", "-.", ":"]

        # Plot each technology's data
        for idx, tech in enumerate(pivot_data.columns):
            plt.plot(
                pivot_data.index,
                pivot_data[tech],
                linestyle=styles[idx % len(styles)],
                label=tech,
            )

        # Adding titles and labels
        plt.title("HN Job Requirements Over Time")
        plt.xlabel("Year")
        plt.ylabel("Job Postings")
        plt.legend(title="Technology")

        # Show the plot
        plt.show()
