"""Big boy library of popular search terms"""

TECHS = {
    "languages": [
        "Python",
        "JavaScript",
        "Java",
        "C#",
        "C++",
        "Go",
        "Kotlin",
        "Swift",
        "TypeScript",
        "Ruby",
        "PHP",
        "Rust",
        "Lua",
        "Matlab",
        "C",
    ],
    "frameworks": [
        "Django",
        "Flask",
        "React",
        "Angular",
        "Vue",
        "Node",
        "Spring Boot",
        "Express",
        "Laravel",
        "Ruby on Rails",
        "Swing",
        "ASP.NET",
        "TensorFlow",
        "PyTorch",
        "Electron",
        "Ember",
    ],
    "databases": [
        "Postgres",
        "MySQL",
        "SQLite",
        "MongoDB",
        "Redis",
        "Oracle",
        "Microsoft SQL Server",
        "Cassandra",
        "Elasticsearch",
        "Firebase",
        "MariaDB",
        "DynamoDB",
        "Couchbase",
        "Neo4j",
    ],
    "web": [
        "HTML",
        "CSS",
        "Sass",
        "Less",
        "Svelte",
        "Bootstrap",
        "Tailwind",
        "Webpack",
        "Babel",
        "Gulp",
        "npm",
        "Yarn",
        "Next.js",
        "Nuxt.js",
        "Gatsby",
    ],
    "old_js_frameworks": [
        "Ember.js",
        "Backbone.js",
        "Knockout.js",
        "Aurelia",
        "Meteor",
        "Durandal",
        "Ractive.js",
        "CanJS",
        "Marionette.js",
        "Spine.js",
    ],
    "mobile": ["Flutter", "React Native", "Swift", "Android", "Kotlin"],
    "misc": [
        "Jenkins",
        "Docker",
        "Kubernetes",
        "Ansible",
        "Terraform",
        "GitLab CI",
        "Travis CI",
        "AWS",
        "Azure",
        "Google Cloud Platform",
        "IBM Cloud",
        "Git",
        "GitHub",
        "GitLab",
        "Bitbucket",
        "JUnit",
        "PyTest",
        "Selenium",
        "Mocha",
        "Jasmine",
        "Jest",
        "RSpec",
        "Xamarin",
        "Pandas",
        "NumPy",
        "Scikit-Learn",
        "TensorFlow",
        "PyTorch",
        "Keras",
        "REST",
        "GraphQL",
        "SOAP",
        "Wordpress",
    ],
}
