"""Big boy library of popular search terms"""

TECHS = {
    "languages": [
        {"name": "Python", "case-sensitive": False, "aliases": []},
        {"name": "JavaScript", "case-sensitive": False, "aliases": []},
        {"name": "Java", "case-sensitive": False, "aliases": []},
        {"name": "C#", "case-sensitive": False, "aliases": []},
        {"name": "C++", "case-sensitive": False, "aliases": []},
        {"name": "Go", "case-sensitive": False, "aliases": []},
        {"name": "Kotlin", "case-sensitive": False, "aliases": []},
        {"name": "Swift", "case-sensitive": False, "aliases": []},
        {"name": "TypeScript", "case-sensitive": False, "aliases": []},
        {"name": "Ruby", "case-sensitive": False, "aliases": []},
        {"name": "PHP", "case-sensitive": False, "aliases": []},
        {"name": "Rust", "case-sensitive": False, "aliases": []},
        {"name": "Lua", "case-sensitive": False, "aliases": []},
        {"name": "Matlab", "case-sensitive": False, "aliases": []},
        {"name": "C", "case-sensitive": False, "aliases": []},
    ],
    "frameworks": [
        {"name": "Django", "case-sensitive": False, "aliases": []},
        {"name": "Flask", "case-sensitive": False, "aliases": []},
        {"name": "React", "case-sensitive": False, "aliases": []},
        {"name": "Angular", "case-sensitive": False, "aliases": []},
        {"name": "Vue", "case-sensitive": False, "aliases": []},
        {"name": "Node", "case-sensitive": False, "aliases": []},
        {"name": "Spring Boot", "case-sensitive": False, "aliases": []},
        {"name": "Express", "case-sensitive": False, "aliases": []},
        {"name": "Laravel", "case-sensitive": False, "aliases": []},
        {"name": "Ruby on Rails", "case-sensitive": False, "aliases": []},
        {"name": "Swing", "case-sensitive": False, "aliases": []},
        {"name": "ASP.NET", "case-sensitive": False, "aliases": []},
        {"name": "TensorFlow", "case-sensitive": False, "aliases": []},
        {"name": "PyTorch", "case-sensitive": False, "aliases": []},
        {"name": "Electron", "case-sensitive": False, "aliases": []},
        {"name": "Ember", "case-sensitive": False, "aliases": []},
    ],
    "databases": [
        {"name": "Postgres", "case-sensitive": False, "aliases": []},
        {"name": "MySQL", "case-sensitive": False, "aliases": []},
        {"name": "SQLite", "case-sensitive": False, "aliases": []},
        {"name": "MongoDB", "case-sensitive": False, "aliases": []},
        {"name": "Redis", "case-sensitive": False, "aliases": []},
        {"name": "Oracle", "case-sensitive": False, "aliases": []},
        {"name": "Microsoft SQL Server", "case-sensitive": False, "aliases": []},
        {"name": "Cassandra", "case-sensitive": False, "aliases": []},
        {"name": "Elasticsearch", "case-sensitive": False, "aliases": []},
        {"name": "Firebase", "case-sensitive": False, "aliases": []},
        {"name": "MariaDB", "case-sensitive": False, "aliases": []},
        {"name": "DynamoDB", "case-sensitive": False, "aliases": []},
        {"name": "Couchbase", "case-sensitive": False, "aliases": []},
        {"name": "Neo4j", "case-sensitive": False, "aliases": []},
    ],
    "web": [
        "HTML",
        {"name": "CSS", "case-sensitive": False, "aliases": []},
        {"name": "Sass", "case-sensitive": False, "aliases": []},
        {"name": "Less", "case-sensitive": False, "aliases": []},
        {"name": "Svelte", "case-sensitive": False, "aliases": []},
        {"name": "Bootstrap", "case-sensitive": False, "aliases": []},
        {"name": "Tailwind", "case-sensitive": False, "aliases": []},
        {"name": "Webpack", "case-sensitive": False, "aliases": []},
        {"name": "Babel", "case-sensitive": False, "aliases": []},
        {"name": "Gulp", "case-sensitive": False, "aliases": []},
        {"name": "npm", "case-sensitive": False, "aliases": []},
        {"name": "Yarn", "case-sensitive": False, "aliases": []},
        {"name": "Next.js", "case-sensitive": False, "aliases": []},
        {"name": "Nuxt.js", "case-sensitive": False, "aliases": []},
        {"name": "Gatsby", "case-sensitive": False, "aliases": []},
    ],
    "old_js_frameworks": [
        {"name": "Ember.js", "case-sensitive": False, "aliases": []},
        {"name": "Backbone.js", "case-sensitive": False, "aliases": []},
        {"name": "Knockout.js", "case-sensitive": False, "aliases": []},
        {"name": "Aurelia", "case-sensitive": False, "aliases": []},
        {"name": "Meteor", "case-sensitive": False, "aliases": []},
        {"name": "Durandal", "case-sensitive": False, "aliases": []},
        {"name": "Ractive.js", "case-sensitive": False, "aliases": []},
        {"name": "CanJS", "case-sensitive": False, "aliases": []},
        {"name": "Marionette.js", "case-sensitive": False, "aliases": []},
        {"name": "Spine.js", "case-sensitive": False, "aliases": []},
    ],
    "mobile": [
        {"name": "Flutter", "case-sensitive": False, "aliases": []},
        {"name": "React Native", "case-sensitive": False, "aliases": []},
        {"name": "Swift", "case-sensitive": False, "aliases": []},
        {"name": "Android", "case-sensitive": False, "aliases": []},
        {"name": "Kotlin", "case-sensitive": False, "aliases": []},
    ],
    "misc": [
        {"name": "Jenkins", "case-sensitive": False, "aliases": []},
        {"name": "Docker", "case-sensitive": False, "aliases": []},
        {"name": "Kubernetes", "case-sensitive": False, "aliases": []},
        {"name": "Ansible", "case-sensitive": False, "aliases": []},
        {"name": "Terraform", "case-sensitive": False, "aliases": []},
        {"name": "GitLab CI", "case-sensitive": False, "aliases": []},
        {"name": "Travis CI", "case-sensitive": False, "aliases": []},
        {"name": "AWS", "case-sensitive": False, "aliases": []},
        {"name": "Azure", "case-sensitive": False, "aliases": []},
        {"name": "Google Cloud Platform", "case-sensitive": False, "aliases": []},
        {"name": "IBM Cloud", "case-sensitive": False, "aliases": []},
        {"name": "Git", "case-sensitive": False, "aliases": []},
        {"name": "GitHub", "case-sensitive": False, "aliases": []},
        {"name": "GitLab", "case-sensitive": False, "aliases": []},
        {"name": "Bitbucket", "case-sensitive": False, "aliases": []},
        {"name": "JUnit", "case-sensitive": False, "aliases": []},
        {"name": "PyTest", "case-sensitive": False, "aliases": []},
        {"name": "Selenium", "case-sensitive": False, "aliases": []},
        {"name": "Mocha", "case-sensitive": False, "aliases": []},
        {"name": "Jasmine", "case-sensitive": False, "aliases": []},
        {"name": "Jest", "case-sensitive": False, "aliases": []},
        {"name": "RSpec", "case-sensitive": False, "aliases": []},
        {"name": "Xamarin", "case-sensitive": False, "aliases": []},
        {"name": "Pandas", "case-sensitive": False, "aliases": []},
        {"name": "NumPy", "case-sensitive": False, "aliases": []},
        {"name": "Scikit-Learn", "case-sensitive": False, "aliases": []},
        {"name": "TensorFlow", "case-sensitive": False, "aliases": []},
        {"name": "PyTorch", "case-sensitive": False, "aliases": []},
        {"name": "Keras", "case-sensitive": False, "aliases": []},
        {"name": "REST", "case-sensitive": False, "aliases": []},
        {"name": "GraphQL", "case-sensitive": False, "aliases": []},
        {"name": "SOAP", "case-sensitive": False, "aliases": []},
        {"name": "Wordpress", "case-sensitive": False, "aliases": []},
    ],
}
